In [1]:
# Import library
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix




In [5]:
data = pd.read_clipboard(sep=',')
data

ip1   ip2   ip3   ip4  tepat
0     2.30  1.97  1.80  1.56  Tidak
1     1.81  1.68  1.57  1.86  Tidak
2     3.07  3.00  2.75  3.21  Tidak
3     2.71  2.33  2.61  1.98  Tidak
4     3.17  3.02  3.28  2.96  Tidak
...    ...   ...   ...   ...    ...
1682  3.07  3.04  3.39  3.55     Ya
1683  3.29  3.22  3.33  3.68     Ya
1684  3.31  3.25  3.44  3.52     Ya
1685  3.44  3.35  3.50  3.50     Ya
1686  3.18  3.05  3.05  3.27     Ya

[1687 rows x 5 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687 entries, 0 to 1686
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ip1     1687 non-null   float64
 1   ip2     1687 non-null   float64
 2   ip3     1687 non-null   float64
 3   ip4     1687 non-null   float64
 4   tepat   1687 non-null   object 
dtypes: float64(4), object(1)
memory usage: 66.0+ KB


In [7]:
data.empty

False

In [9]:
#ubah data bakat jd numerik
en = LabelEncoder()

data['tepat'] = en.fit_transform(data['tepat'])
data

ip1   ip2   ip3   ip4  tepat
0     2.30  1.97  1.80  1.56      0
1     1.81  1.68  1.57  1.86      0
2     3.07  3.00  2.75  3.21      0
3     2.71  2.33  2.61  1.98      0
4     3.17  3.02  3.28  2.96      0
...    ...   ...   ...   ...    ...
1682  3.07  3.04  3.39  3.55      1
1683  3.29  3.22  3.33  3.68      1
1684  3.31  3.25  3.44  3.52      1
1685  3.44  3.35  3.50  3.50      1
1686  3.18  3.05  3.05  3.27      1

[1687 rows x 5 columns]

In [10]:
#mnntukn dta x dn y
x = data.iloc[:, :-1].values #mngmbil nilai kcuali pd klom trakhir
y = data.iloc[:, -1].values #hny mngmbil nilai pd klom trakhir

In [11]:
x

array([[2.3 , 1.97, 1.8 , 1.56],
       [1.81, 1.68, 1.57, 1.86],
       [3.07, 3.  , 2.75, 3.21],
       ...,
       [3.31, 3.25, 3.44, 3.52],
       [3.44, 3.35, 3.5 , 3.5 ],
       [3.18, 3.05, 3.05, 3.27]])

In [12]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [13]:
#splitting data
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=123)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  1349
x_test =  338
y_train =  1349
y_test =  338


In [14]:
#pengskalaan nilai pada data pke standard scaller

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
x_train

array([[-0.02107197,  0.62586221, -0.70064368, -0.53934535],
       [-1.02434578, -1.65535776, -3.06720536, -3.78590748],
       [ 0.31335263,  0.47521561,  0.7860425 ,  0.65023467],
       ...,
       [ 0.28548391,  0.04479674,  0.05786968,  0.08022758],
       [ 0.00679674,  0.30304806,  0.05786968,  0.551103  ],
       [ 0.61990851,  0.8195507 ,  0.90740464,  0.47675425]])

In [16]:
x_test

array([[-0.60631502, -0.45018495, -0.03315193, -0.21716743],
       [-1.08008321, -0.14889174,  0.6039993 ,  0.05544466],
       [-0.18828427,  0.08783863,  0.51297769,  0.45197133],
       ...,
       [-0.52270887, -0.68691532, -0.42757887,  0.00587882],
       [ 0.50843365,  1.01323919,  1.15012892,  0.20414216],
       [ 1.31662643,  0.84107164,  0.96808571,  0.99719551]])

In [17]:
y_train

array([0, 1, 1, ..., 1, 1, 1])

In [18]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [19]:
#training model pke nb

classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [20]:
#prediksi
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [21]:
#predik probabilitas
classifier.predict_proba(x_test)

array([[4.53874745e-02, 9.54612526e-01],
       [3.98687601e-02, 9.60131240e-01],
       [1.80324546e-02, 9.81967545e-01],
       [5.00411212e-02, 9.49958879e-01],
       [7.88149714e-02, 9.21185029e-01],
       [9.99935784e-01, 6.42159248e-05],
       [1.56969941e-02, 9.84303006e-01],
       [1.77181293e-02, 9.82281871e-01],
       [1.07468451e-02, 9.89253155e-01],
       [1.01446439e-02, 9.89855356e-01],
       [2.22226084e-02, 9.77777392e-01],
       [1.35336082e-02, 9.86466392e-01],
       [1.20335604e-02, 9.87966440e-01],
       [1.28186995e-02, 9.87181300e-01],
       [1.79271585e-02, 9.82072841e-01],
       [1.29500376e-02, 9.87049962e-01],
       [3.05955116e-02, 9.69404488e-01],
       [1.59886015e-02, 9.84011398e-01],
       [2.19868392e-02, 9.78013161e-01],
       [8.07777507e-01, 1.92222493e-01],
       [1.39810711e-02, 9.86018929e-01],
       [1.55153099e-02, 9.84484690e-01],
       [2.66489087e-02, 9.73351091e-01],
       [1.60638071e-02, 9.83936193e-01],
       [8.802414

In [22]:
#evaluasi
#confusion matriks
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[  4  13]
 [ 18 303]]


In [23]:
#evaluasi
#clasification report
akurasi = classification_report(y_test, y_pred)
akurasi

'              precision    recall  f1-score   support\n\n           0       0.18      0.24      0.21        17\n           1       0.96      0.94      0.95       321\n\n    accuracy                           0.91       338\n   macro avg       0.57      0.59      0.58       338\nweighted avg       0.92      0.91      0.91       338\n'

In [24]:
#lht akurasi 
akurasi = accuracy_score(y_test, y_pred)
print("tingkat akurasi = %d persen"%(akurasi*100))

tingkat akurasi = 90 persen


In [25]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)

ydata

y_test  y_pred
0         1       1
1         1       1
2         1       1
3         1       1
4         1       1
..      ...     ...
333       1       1
334       1       1
335       1       1
336       1       1
337       1       1

[338 rows x 2 columns]